version: '3'
services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ${APP_NAME}_php
    restart: unless-stopped
    environment:
      SERVICE_NAME: ${APP_NAME}
      SERVICE_TAGS: ${APP_ENV}
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app_network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}_nginx
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
      - proxy_reverse

  # Mariadb Service
  database:
    image: mariadb:latest
    container_name: ${APP_NAME}_database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVICE_TAGS: ${APP_ENV}
      SERVICE_NAME: mysql
    volumes:
      - ./storage-db:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app_network

  # Redis service
  redis:
    image: redis:latest
    container_name: ${APP_NAME}_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
    networks:
      - app_network

# Docker Networks
networks:
  app_network:
    driver: bridge
  proxy_reverse:
    external:
      name: proxy_reverse
